version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    volumes:
      - static:/frontend_static
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
  # Добавляем новый контейнер: gateway
  gateway:
    # Сбилдить и запустить образ,
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    ports:
      - 8000:80
